=== dsommerville-illumio/resilient-community-apps/fn_illumio/payload_samples/illumio_create_virtual_service/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "object",
      "properties": {
        "href": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "created_at": {
          "type": "string"
        },
        "updated_at": {
          "type": "string"
        },
        "update_type": {
          "type": "string"
        },
        "created_by": {
          "type": "object",
          "properties": {
            "href": {
              "type": "string"
            }
          }
        },
        "updated_by": {
          "type": "object",
          "properties": {
            "href": {
              "type": "string"
            }
          }
        },
        "caps": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "apply_to": {
          "type": "string"
        },
        "service_ports": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "port": {
                "type": "integer"
              },
              "proto": {
                "type": "integer"
              }
            }
          }
        },
        "ip_overrides": {
          "type": "array"
        }
      }
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "illumio_protocol": {
          "type": "string"
        },
        "illumio_port": {
          "type": "integer"
        },
        "illumio_virtual_service_name": {
          "type": "string"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== dsommerville-illumio/resilient-community-apps/fn_illumio/payload_samples/illumio_create_virtual_service/output_json_example.json
{
    "version": 2.0,
    "success": true,
    "reason": null,
    "content": {
        "href": "/orgs/1/sec_policy/draft/virtual_services/575f43f4-3f99-4bb0-8a6f-9e2da7a9fbd2",
        "name": "VS-IBM-SOAR-3389-TCP",
        "created_at": "2022-01-07T15:23:17.885Z",
        "updated_at": "2022-01-07T15:23:17.897Z",
        "update_type": "create",
        "created_by": {
            "href": "/users/464"
        },
        "updated_by": {
            "href": "/users/464"
        },
        "caps": [
            "write",
            "provision",
            "delete"
        ],
        "apply_to": "host_only",
        "service_ports": [
            {
                "port": 3389,
                "proto": 6
            }
        ],
        "ip_overrides": []
    },
    "raw": null,
    "inputs": {
        "illumio_protocol": "TCP",
        "illumio_port": 3389,
        "illumio_virtual_service_name": "VS-IBM-SOAR-3389-TCP"
    },
    "metrics": {
        "version": "1.0",
        "package": "fn-illumio",
        "package_version": "1.0.0",
        "host": "C02G82JEMD6R",
        "execution_time_ms": 658,
        "timestamp": "2022-01-07 10:23:17"
    }
}
