=== dsommerville-illumio/resilient-community-apps/fn_illumio/payload_samples/illumio_create_ip_list/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "object",
      "properties": {
        "href": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "created_at": {
          "type": "string"
        },
        "updated_at": {
          "type": "string"
        },
        "update_type": {
          "type": "string"
        },
        "created_by": {
          "type": "object",
          "properties": {
            "href": {
              "type": "string"
            }
          }
        },
        "updated_by": {
          "type": "object",
          "properties": {
            "href": {
              "type": "string"
            }
          }
        },
        "ip_ranges": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "from_ip": {
                "type": "string"
              },
              "exclusion": {
                "type": "boolean"
              },
              "to_ip": {
                "type": "string"
              }
            }
          }
        },
        "fqdns": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "fqdn": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "illumio_ip_list_ip_ranges": {
          "type": "string"
        },
        "illumio_ip_list_name": {
          "type": "string"
        },
        "illumio_ip_list_description": {
          "type": "string"
        },
        "illumio_ip_list_fqdns": {
          "type": "string"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== dsommerville-illumio/resilient-community-apps/fn_illumio/payload_samples/illumio_get_ip_lists/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "ip_lists": [
      {
        "href": "/orgs/28/sec_policy/active/ip_lists/105",
        "name": "Any (0.0.0.0/0 and ::/0)",
        "created_at": "2021-06-29T17:13:12.054Z",
        "updated_at": "2021-06-29T17:13:12.064Z",
        "created_by": {
          "href": "/users/0"
        },
        "updated_by": {
          "href": "/users/0"
        },
        "ip_ranges": [
          {
            "from_ip": "0.0.0.0/0",
            "exclusion": false
          },
          {
            "from_ip": "::/0",
            "exclusion": false
          }
        ],
        "fqdns": []
      }
    ]
  },
  "raw": null,
  "inputs": {
    "illumio_max_results": 1,
    "illumio_ip_list_name": "Any (0.0.0.0/0 and ::/0)"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-illumio",
    "package_version": "1.1.0",
    "host": "C02G82JEMD6R",
    "execution_time_ms": 690,
    "timestamp": "2022-03-09 23:57:59"
  }
}

=== dsommerville-illumio/resilient-community-apps/fn_illumio/payload_samples/illumio_create_ip_list/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "href": "/orgs/28/sec_policy/draft/ip_lists/2335",
    "name": "IPL-LAB",
    "description": "",
    "created_at": "2022-03-10T04:33:50.982Z",
    "updated_at": "2022-03-10T04:33:50.989Z",
    "update_type": "create",
    "created_by": {
      "href": "/users/520"
    },
    "updated_by": {
      "href": "/users/520"
    },
    "ip_ranges": [
      {
        "from_ip": "10.2.24.0/28",
        "exclusion": false
      },
      {
        "from_ip": "10.8.16.192",
        "to_ip": "10.8.16.212",
        "exclusion": false
      },
      {
        "from_ip": "10.10.0.146",
        "exclusion": false
      }
    ],
    "fqdns": [
      {
        "fqdn": "ibmsoar.lab.com"
      },
      {
        "fqdn": "apphost.lab.com"
      }
    ]
  },
  "raw": null,
  "inputs": {
    "illumio_ip_list_ip_ranges": "10.2.24.0/28,10.8.16.192-10.8.16.212,10.10.0.146",
    "illumio_ip_list_name": "IPL-LAB",
    "illumio_ip_list_description": "",
    "illumio_ip_list_fqdns": "ibmsoar.lab.com,apphost.lab.com"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-illumio",
    "package_version": "1.1.0",
    "host": "C02G82JEMD6R",
    "execution_time_ms": 812,
    "timestamp": "2022-03-09 23:33:50"
  }
}

=== dsommerville-illumio/resilient-community-apps/fn_illumio/payload_samples/illumio_provision_objects/output_json_example.json
{
    "version": 2.0,
    "success": true,
    "reason": null,
    "content": {
        "provisioned_hrefs": [
            "/orgs/1/sec_policy/active/virtual_services/575f43f4-3f99-4bb0-8a6f-9e2da7a9fbd2"
        ]
    },
    "raw": null,
    "inputs": {
        "illumio_policy_object_hrefs": "/orgs/1/sec_policy/draft/virtual_services/575f43f4-3f99-4bb0-8a6f-9e2da7a9fbd2"
    },
    "metrics": {
        "version": "1.0",
        "package": "fn-illumio",
        "package_version": "1.0.0",
        "host": "C02G82JEMD6R",
        "execution_time_ms": 490,
        "timestamp": "2022-01-07 10:23:20"
    }
}

=== dsommerville-illumio/resilient-community-apps/fn_illumio/payload_samples/illumio_create_enforcement_boundary/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "href": "/orgs/28/sec_policy/active/enforcement_boundaries/1325",
    "name": "EB-IBM-SOAR-3389-TCP",
    "created_at": "2022-03-04T18:46:17.900Z",
    "updated_at": "2022-03-04T18:46:17.909Z",
    "created_by": {
      "href": "/users/520"
    },
    "updated_by": {
      "href": "/users/520"
    },
    "caps": [
      "write",
      "provision"
    ],
    "ingress_services": [
      {
        "port": 3389,
        "proto": 6
      }
    ],
    "providers": [
      {
        "actors": "ams"
      }
    ],
    "consumers": [
      {
        "ip_list": {
          "href": "/orgs/28/sec_policy/active/ip_lists/105"
        }
      }
    ]
  },
  "raw": null,
  "inputs": {
    "illumio_protocol": "TCP",
    "illumio_enforcement_boundary_providers": "ams",
    "illumio_enforcement_boundary_name": "EB-IBM-SOAR-3389-TCP",
    "illumio_port": 3389,
    "illumio_enforcement_boundary_consumers": "/orgs/28/sec_policy/active/ip_lists/105"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-illumio",
    "package_version": "1.1.0",
    "host": "C02G82JEMD6R",
    "execution_time_ms": 538,
    "timestamp": "2022-03-09 23:58:26"
  }
}
