=== dsommerville-illumio/resilient-community-apps/fn_illumio/payload_samples/illumio_get_workloads/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "object",
      "properties": {
        "workloads": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "href": {
                "type": "string"
              },
              "created_at": {
                "type": "string"
              },
              "updated_at": {
                "type": "string"
              },
              "created_by": {
                "type": "object",
                "properties": {
                  "href": {
                    "type": "string"
                  }
                }
              },
              "updated_by": {
                "type": "object",
                "properties": {
                  "href": {
                    "type": "string"
                  }
                }
              },
              "caps": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "hostname": {
                "type": "string"
              },
              "public_ip": {
                "type": "string"
              },
              "interfaces": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "address": {
                      "type": "string"
                    },
                    "cidr_block": {
                      "type": "integer"
                    },
                    "network": {
                      "type": "object",
                      "properties": {
                        "href": {
                          "type": "string"
                        }
                      }
                    },
                    "network_detection_mode": {
                      "type": "string"
                    },
                    "loopback": {
                      "type": "boolean"
                    },
                    "default_gateway_address": {
                      "type": "string"
                    }
                  }
                }
              },
              "service_provider": {
                "type": "string"
              },
              "data_center": {
                "type": "string"
              },
              "data_center_zone": {
                "type": "string"
              },
              "os_id": {
                "type": "string"
              },
              "os_detail": {
                "type": "string"
              },
              "online": {
                "type": "boolean"
              },
              "deleted": {
                "type": "boolean"
              },
              "ignored_interface_names": {
                "type": "array"
              },
              "containers_inherit_host_policy": {
                "type": "boolean"
              },
              "blocked_connection_action": {
                "type": "string"
              },
              "labels": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "href": {
                      "type": "string"
                    }
                  }
                }
              },
              "services": {
                "type": "object"
              },
              "agent": {
                "type": "object",
                "properties": {
                  "href": {
                    "type": "string"
                  },
                  "config": {
                    "type": "object",
                    "properties": {
                      "mode": {
                        "type": "string"
                      },
                      "log_traffic": {
                        "type": "boolean"
                      },
                      "visibility_level": {
                        "type": "string"
                      }
                    }
                  },
                  "status": {
                    "type": "object",
                    "properties": {
                      "status": {
                        "type": "string"
                      },
                      "uid": {
                        "type": "string"
                      },
                      "instance_id": {
                        "type": "string"
                      },
                      "last_heartbeat_on": {
                        "type": "string"
                      },
                      "uptime_seconds": {
                        "type": "integer"
                      },
                      "agent_version": {
                        "type": "string"
                      },
                      "managed_since": {
                        "type": "string"
                      },
                      "fw_config_current": {
                        "type": "boolean"
                      },
                      "firewall_rule_count": {
                        "type": "integer"
                      },
                      "security_policy_refresh_at": {
                        "type": "string"
                      },
                      "security_policy_applied_at": {
                        "type": "string"
                      },
                      "security_policy_received_at": {
                        "type": "string"
                      },
                      "agent_health_errors": {
                        "type": "object",
                        "properties": {
                          "errors": {
                            "type": "array"
                          },
                          "warnings": {
                            "type": "array"
                          }
                        }
                      },
                      "agent_health": {
                        "type": "array"
                      },
                      "security_policy_sync_state": {
                        "type": "string"
                      }
                    }
                  },
                  "unpair_allowed": {
                    "type": "boolean"
                  },
                  "type": {
                    "type": "string"
                  }
                }
              },
              "ven": {
                "type": "object",
                "properties": {
                  "href": {
                    "type": "string"
                  }
                }
              },
              "enforcement_mode": {
                "type": "string"
              },
              "visibility_level": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "illumio_workload_enforcement_mode": {
          "type": "string"
        },
        "illumio_workload_managed": {
          "type": "boolean"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== dsommerville-illumio/resilient-community-apps/fn_illumio/payload_samples/illumio_get_workloads/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "workloads": [
      {
        "href": "/orgs/28/workloads/1fbe5dee-8bde-49cc-9a8f-6870a05a716e",
        "created_at": "2022-01-28T22:54:18.034216Z",
        "updated_at": "2022-03-10T04:23:57.441191Z",
        "created_by": {
          "href": "/orgs/28/agents/130678"
        },
        "updated_by": {
          "href": "/orgs/28/agents/130678"
        },
        "caps": [
          "write"
        ],
        "hostname": "core-lb-3",
        "public_ip": "44.228.236.80",
        "interfaces": [
          {
            "name": "eth0.public",
            "address": "44.228.236.80",
            "cidr_block": 32,
            "network": {
              "href": "/orgs/28/networks/15ef3cf8-9210-4174-9628-472efa09cd30"
            },
            "network_detection_mode": "manual",
            "loopback": false
          },
          {
            "name": "eth0",
            "address": "fe80::426:2bff:fe53:b045",
            "cidr_block": 64,
            "network": {
              "href": "/orgs/28/networks/238e7063-547a-4d54-bfd8-cd4227273168"
            },
            "network_detection_mode": "link_local",
            "loopback": false
          },
          {
            "name": "eth0",
            "address": "10.1.0.220",
            "cidr_block": 24,
            "default_gateway_address": "10.1.0.1",
            "network": {
              "href": "/orgs/28/networks/15ef3cf8-9210-4174-9628-472efa09cd30"
            },
            "network_detection_mode": "single_private_brn",
            "loopback": false
          }
        ],
        "service_provider": "amazonaws.com",
        "data_center": "us-west-2.amazonaws.com",
        "data_center_zone": "us-west-2a",
        "os_id": "ubuntu-x86_64-xenial",
        "os_detail": "5.4.0-1038-aws #40-Ubuntu SMP Fri Feb 5 23:50:40 UTC 2021 (Ubuntu 20.04.2 LTS)",
        "online": true,
        "deleted": false,
        "ignored_interface_names": [],
        "containers_inherit_host_policy": false,
        "blocked_connection_action": "drop",
        "labels": [
          {
            "href": "/orgs/28/labels/21481"
          },
          {
            "href": "/orgs/28/labels/21480"
          },
          {
            "href": "/orgs/28/labels/21479"
          },
          {
            "href": "/orgs/28/labels/21487"
          }
        ],
        "services": {},
        "agent": {
          "href": "/orgs/28/agents/130678",
          "config": {
            "mode": "illuminated",
            "log_traffic": false,
            "visibility_level": "flow_summary"
          },
          "status": {
            "status": "active",
            "uid": "us-west-2a+i-007ff950e17c8f31b",
            "instance_id": "i-007ff950e17c8f31b",
            "last_heartbeat_on": "2022-03-10T04:58:30.763908Z",
            "uptime_seconds": 3480231,
            "agent_version": "21.2.0-7831",
            "managed_since": "2022-01-28T22:54:18.044689Z",
            "fw_config_current": true,
            "firewall_rule_count": 0,
            "security_policy_refresh_at": "2022-03-10T04:24:03.073369Z",
            "security_policy_applied_at": "2022-03-10T04:24:03.073369Z",
            "security_policy_received_at": "2022-03-10T04:24:03.073369Z",
            "agent_health_errors": {
              "errors": [],
              "warnings": []
            },
            "agent_health": [],
            "security_policy_sync_state": "applied"
          },
          "unpair_allowed": true,
          "type": "Host"
        },
        "ven": {
          "href": "/orgs/28/vens/1fbe5dee-8bde-49cc-9a8f-6870a05a716e"
        },
        "enforcement_mode": "visibility_only",
        "visibility_level": "flow_summary"
      },
      {
        "href": "/orgs/28/workloads/424b21c5-f8c7-40d0-b2bd-53fd38f606c6",
        "created_at": "2022-01-28T22:54:52.29287Z",
        "updated_at": "2022-03-10T04:23:57.48183Z",
        "created_by": {
          "href": "/orgs/28/agents/131033"
        },
        "updated_by": {
          "href": "/orgs/28/agents/131033"
        },
        "caps": [
          "write"
        ],
        "hostname": "linux-jumpbox-1",
        "public_ip": "52.38.62.142",
        "interfaces": [
          {
            "name": "eth0",
            "address": "10.1.100.165",
            "cidr_block": 24,
            "default_gateway_address": "10.1.100.1",
            "network": {
              "href": "/orgs/28/networks/15ef3cf8-9210-4174-9628-472efa09cd30"
            },
            "network_detection_mode": "single_private_brn",
            "loopback": false
          },
          {
            "name": "eth0.public",
            "address": "52.38.62.142",
            "cidr_block": 32,
            "network": {
              "href": "/orgs/28/networks/15ef3cf8-9210-4174-9628-472efa09cd30"
            },
            "network_detection_mode": "manual",
            "loopback": false
          },
          {
            "name": "eth0",
            "address": "fe80::4a5:31ff:fe7a:bbdd",
            "cidr_block": 64,
            "network": {
              "href": "/orgs/28/networks/238e7063-547a-4d54-bfd8-cd4227273168"
            },
            "network_detection_mode": "link_local",
            "loopback": false
          }
        ],
        "service_provider": "amazonaws.com",
        "data_center": "us-west-2.amazonaws.com",
        "data_center_zone": "us-west-2a",
        "os_id": "ubuntu-x86_64-xenial",
        "os_detail": "5.13.0-1014-aws #15~20.04.1-Ubuntu SMP Thu Feb 10 17:55:03 UTC 2022 (Ubuntu 20.04.4 LTS)",
        "online": true,
        "deleted": false,
        "ignored_interface_names": [],
        "containers_inherit_host_policy": false,
        "blocked_connection_action": "drop",
        "labels": [
          {
            "href": "/orgs/28/labels/21495"
          },
          {
            "href": "/orgs/28/labels/21494"
          },
          {
            "href": "/orgs/28/labels/21481"
          },
          {
            "href": "/orgs/28/labels/21480"
          }
        ],
        "services": {},
        "agent": {
          "href": "/orgs/28/agents/131033",
          "config": {
            "mode": "illuminated",
            "log_traffic": false,
            "visibility_level": "flow_summary"
          },
          "status": {
            "status": "active",
            "uid": "us-west-2a+i-0786119bf8d4dfda7",
            "instance_id": "i-0786119bf8d4dfda7",
            "last_heartbeat_on": "2022-03-10T04:58:30.298617Z",
            "uptime_seconds": 475179,
            "agent_version": "21.2.0-7831",
            "managed_since": "2022-01-28T22:54:52.303542Z",
            "fw_config_current": true,
            "firewall_rule_count": 0,
            "security_policy_refresh_at": "2022-03-10T04:24:03.493791Z",
            "security_policy_applied_at": "2022-03-10T04:24:03.493791Z",
            "security_policy_received_at": "2022-03-10T04:24:03.493791Z",
            "agent_health_errors": {
              "errors": [],
              "warnings": []
            },
            "agent_health": [],
            "security_policy_sync_state": "applied"
          },
          "unpair_allowed": true,
          "type": "Host"
        },
        "ven": {
          "href": "/orgs/28/vens/424b21c5-f8c7-40d0-b2bd-53fd38f606c6"
        },
        "enforcement_mode": "visibility_only",
        "visibility_level": "flow_summary"
      },
      {
        "href": "/orgs/28/workloads/0c2ee289-3f07-4842-97fa-2acf9d8f837c",
        "created_at": "2022-01-28T22:54:17.016051Z",
        "updated_at": "2022-03-10T04:23:57.562762Z",
        "created_by": {
          "href": "/orgs/28/agents/130675"
        },
        "updated_by": {
          "href": "/orgs/28/agents/130675"
        },
        "caps": [
          "write"
        ],
        "hostname": "core-lb-1",
        "public_ip": "44.228.236.80",
        "interfaces": [
          {
            "name": "eth0.public",
            "address": "44.228.236.80",
            "cidr_block": 32,
            "network": {
              "href": "/orgs/28/networks/15ef3cf8-9210-4174-9628-472efa09cd30"
            },
            "network_detection_mode": "manual",
            "loopback": false
          },
          {
            "name": "eth0",
            "address": "fe80::4d6:ceff:fee1:1367",
            "cidr_block": 64,
            "network": {
              "href": "/orgs/28/networks/238e7063-547a-4d54-bfd8-cd4227273168"
            },
            "network_detection_mode": "link_local",
            "loopback": false
          },
          {
            "name": "eth0",
            "address": "10.1.0.150",
            "cidr_block": 24,
            "default_gateway_address": "10.1.0.1",
            "network": {
              "href": "/orgs/28/networks/15ef3cf8-9210-4174-9628-472efa09cd30"
            },
            "network_detection_mode": "single_private_brn",
            "loopback": false
          }
        ],
        "service_provider": "amazonaws.com",
        "data_center": "us-west-2.amazonaws.com",
        "data_center_zone": "us-west-2a",
        "os_id": "ubuntu-x86_64-xenial",
        "os_detail": "5.4.0-1038-aws #40-Ubuntu SMP Fri Feb 5 23:50:40 UTC 2021 (Ubuntu 20.04.2 LTS)",
        "online": true,
        "deleted": false,
        "ignored_interface_names": [],
        "containers_inherit_host_policy": false,
        "blocked_connection_action": "drop",
        "labels": [
          {
            "href": "/orgs/28/labels/21481"
          },
          {
            "href": "/orgs/28/labels/21480"
          },
          {
            "href": "/orgs/28/labels/21479"
          },
          {
            "href": "/orgs/28/labels/21487"
          }
        ],
        "services": {},
        "agent": {
          "href": "/orgs/28/agents/130675",
          "config": {
            "mode": "illuminated",
            "log_traffic": false,
