=== dsommerville-illumio/resilient-community-apps/fn_illumio/payload_samples/illumio_run_traffic_analysis/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "object",
      "properties": {
        "traffic_flows": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "src": {
                "type": "object",
                "properties": {
                  "ip": {
                    "type": "string"
                  },
                  "ip_lists": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "href": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              },
              "dst": {
                "type": "object",
                "properties": {
                  "ip": {
                    "type": "string"
                  },
                  "workload": {
                    "type": "object",
                    "properties": {
                      "href": {
                        "type": "string"
                      },
                      "hostname": {
                        "type": "string"
                      },
                      "os_type": {
                        "type": "string"
                      },
                      "labels": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "href": {
                              "type": "string"
                            },
                            "key": {
                              "type": "string"
                            },
                            "value": {
                              "type": "string"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              },
              "service": {
                "type": "object",
                "properties": {
                  "port": {
                    "type": "integer"
                  },
                  "proto": {
                    "type": "integer"
                  },
                  "process_name": {
                    "type": "string"
                  },
                  "windows_service_name": {
                    "type": "string"
                  },
                  "user_name": {
                    "type": "string"
                  }
                }
              },
              "num_connections": {
                "type": "integer"
              },
              "state": {
                "type": "string"
              },
              "timestamp_range": {
                "type": "object",
                "properties": {
                  "first_detected": {
                    "type": "string"
                  },
                  "last_detected": {
                    "type": "string"
                  }
                }
              },
              "dst_bi": {
                "type": "integer"
              },
              "dst_bo": {
                "type": "integer"
              },
              "policy_decision": {
                "type": "string"
              },
              "flow_direction": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "illumio_protocol": {
          "type": "string"
        },
        "illumio_traffic_analysis_policy_decisions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "illumio_traffic_analysis_end_time": {
          "type": "integer"
        },
        "illumio_traffic_analysis_start_time": {
          "type": "integer"
        },
        "illumio_port": {
          "type": "integer"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== dsommerville-illumio/resilient-community-apps/fn_illumio/payload_samples/illumio_run_traffic_analysis/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "traffic_flows": [
      {
        "src": {
          "ip": "176.9.150.138",
          "ip_lists": [
            {
              "href": "/orgs/28/sec_policy/draft/ip_lists/2191",
              "name": "Internet"
            }
          ]
        },
        "dst": {
          "ip": "10.1.100.149",
          "workload": {
            "href": "/orgs/28/workloads/7c78ab4b-ced8-43a7-bf1f-5e92f89138bf",
            "hostname": "windows-jumpbox-1",
            "os_type": "windows",
            "labels": [
              {
                "href": "/orgs/28/labels/21494",
                "key": "app",
                "value": "Administration"
              },
              {
                "href": "/orgs/28/labels/21480",
                "key": "env",
                "value": "Production"
              },
              {
                "href": "/orgs/28/labels/21481",
                "key": "loc",
                "value": "Dallas"
              },
              {
                "href": "/orgs/28/labels/21495",
                "key": "role",
                "value": "Jump Server"
              }
            ]
          }
        },
        "service": {
          "port": 3389,
          "proto": 6,
          "process_name": "svchost.exe",
          "windows_service_name": "TermService",
          "user_name": "NETWORK SERVICE"
        },
        "num_connections": 1,
        "state": "timed out",
        "timestamp_range": {
          "first_detected": "2022-02-03T22:33:52Z",
          "last_detected": "2022-02-03T22:33:52Z"
        },
        "dst_bi": 0,
        "dst_bo": 0,
        "policy_decision": "potentially_blocked",
        "flow_direction": "inbound"
      },
      {
        "src": {
          "ip": "20.107.24.45",
          "ip_lists": [
            {
              "href": "/orgs/28/sec_policy/draft/ip_lists/2191",
              "name": "Internet"
            }
          ]
        },
        "dst": {
          "ip": "10.1.100.149",
          "workload": {
            "href": "/orgs/28/workloads/7c78ab4b-ced8-43a7-bf1f-5e92f89138bf",
            "hostname": "windows-jumpbox-1",
            "os_type": "windows",
            "labels": [
              {
                "href": "/orgs/28/labels/21494",
                "key": "app",
                "value": "Administration"
              },
              {
                "href": "/orgs/28/labels/21480",
                "key": "env",
                "value": "Production"
              },
              {
                "href": "/orgs/28/labels/21481",
                "key": "loc",
                "value": "Dallas"
              },
              {
                "href": "/orgs/28/labels/21495",
                "key": "role",
                "value": "Jump Server"
              }
            ]
          }
        },
        "service": {
          "port": 3389,
          "proto": 6,
          "process_name": "svchost.exe",
          "windows_service_name": "TermService",
          "user_name": "NETWORK SERVICE"
        },
        "num_connections": 1,
        "state": "timed out",
        "timestamp_range": {
          "first_detected": "2022-02-03T22:33:53Z",
          "last_detected": "2022-02-03T22:33:53Z"
        },
        "dst_bi": 0,
        "dst_bo": 0,
        "policy_decision": "potentially_blocked",
        "flow_direction": "inbound"
      },
      {
        "src": {
          "ip": "193.56.146.208",
          "ip_lists": [
            {
              "href": "/orgs/28/sec_policy/draft/ip_lists/2191",
              "name": "Internet"
            }
          ]
        },
        "dst": {
          "ip": "10.1.100.149",
          "workload": {
            "href": "/orgs/28/workloads/7c78ab4b-ced8-43a7-bf1f-5e92f89138bf",
            "hostname": "windows-jumpbox-1",
            "os_type": "windows",
            "labels": [
              {
                "href": "/orgs/28/labels/21494",
                "key": "app",
                "value": "Administration"
              },
              {
                "href": "/orgs/28/labels/21480",
                "key": "env",
                "value": "Production"
              },
              {
                "href": "/orgs/28/labels/21481",
                "key": "loc",
                "value": "Dallas"
              },
              {
                "href": "/orgs/28/labels/21495",
                "key": "role",
                "value": "Jump Server"
              }
            ]
          }
        },
        "service": {
          "port": 3389,
          "proto": 6,
          "process_name": "svchost.exe",
          "windows_service_name": "TermService",
          "user_name": "NETWORK SERVICE"
        },
        "num_connections": 7,
        "state": "active",
        "timestamp_range": {
          "first_detected": "2022-02-03T22:34:04Z",
          "last_detected": "2022-02-03T22:34:04Z"
        },
        "dst_bi": 0,
        "dst_bo": 0,
        "policy_decision": "potentially_blocked",
        "flow_direction": "inbound"
      },
      {
        "src": {
          "ip": "193.56.146.208",
          "ip_lists": [
            {
              "href": "/orgs/28/sec_policy/draft/ip_lists/2191",
              "name": "Internet"
            }
          ]
        },
        "dst": {
          "ip": "10.1.100.149",
          "workload": {
            "href": "/orgs/28/workloads/7c78ab4b-ced8-43a7-bf1f-5e92f89138bf",
            "hostname": "windows-jumpbox-1",
            "os_type": "windows",
            "labels": [
              {
                "href": "/orgs/28/labels/21494",
                "key": "app",
                "value": "Administration"
              },
              {
                "href": "/orgs/28/labels/21480",
                "key": "env",
                "value": "Production"
              },
              {
                "href": "/orgs/28/labels/21481",
                "key": "loc",
                "value": "Dallas"
              },
              {
                "href": "/orgs/28/labels/21495",
                "key": "role",
                "value": "Jump Server"
              }
            ]
          }
        },
        "service": {
          "port": 3389,
          "proto": 6,
          "process_name": "svchost.exe",
          "windows_service_name": "TermService",
          "user_name": "NETWORK SERVICE"
        },
        "num_connections": 23,
        "state": "timed out",
        "timestamp_range": {
          "first_detected": "2022-02-03T22:34:25Z",
          "last_detected": "2022-02-03T22:34:25Z"
        },
        "dst_bi": 0,
        "dst_bo": 0,
        "policy_decision": "potentially_blocked",
        "flow_direction": "inbound"
      },
      {
        "src": {
          "ip": "34.222.179.17",
          "ip_lists": [
            {
              "href": "/orgs/28/sec_policy/draft/ip_lists/2191",
              "name": "Internet"
            }
          ]
        },
        "dst": {
          "ip": "10.1.100.149",
          "workload": {
            "href": "/orgs/28/workloads/7c78ab4b-ced8-43a7-bf1f-5e92f89138bf",
            "hostname": "windows-jumpbox-1",
            "os_type": "windows",
            "labels": [
              {
                "href": "/orgs/28/labels/21494",
                "key": "app",
                "value": "Administration"
              },
              {
                "href": "/orgs/28/labels/21480",
                "key": "env",
                "value": "Production"
              },
              {
                "href": "/orgs/28/labels/21481",
                "key": "loc",
                "value": "Dallas"
              },
              {
                "href": "/orgs/28/labels/21495",
                "key": "role",
                "value": "Jump Server"
              }
            ]
          }
        },
        "service": {
          "port": 3389,
          "proto": 6,
          "process_name": "svchost.exe",
          "windows_service_name": "TermService",
          "user_name": "NETWORK SERVICE"
        },
        "num_connections": 1,
        "state": "timed out",
        "timestamp_range": {
          "first_detected": "2022-02-03T22:33:55Z",
          "last_detected": "2022-02-03T22:33:55Z"
        },
        "dst_bi": 0,
        "dst_bo": 0,
        "policy_decision": "potentially_blocked",
        "flow_direction": "inbound"
      },
      {
        "src": {
          "ip": "20.112.109.175",
          "ip_lists": [
            {
              "href": "/orgs/28/sec_policy/draft/ip_lists/2191",
              "name": "Internet"
            }
          ]
        },
        "dst": {
          "ip": "10.1.100.149",
          "workload": {
            "href": "/orgs/28/workloads/7c78ab4b-ced8-43a7-bf1f-5e92f89138bf",
            "hostname": "windows-jumpbox-1",
            "os_type": "windows",
            "labels": [
              {
                "href": "/orgs/28/labels/21494",
                "key": "app",
                "value": "Administration"
              },
              {
                "href": "/orgs/28/labels/21480",
                "key": "env",
                "value": "Production"
              },
              {
                "href": "/orgs/28/labels/21481",
                "key": "loc",
                "value": "Dallas"
              },
              {
                "href": "/orgs/28/labels/21495",
                "key": "role",
                "value": "Jump Server"
              }
            ]
          }
        },
        "service": {
          "port": 3389,
          "proto": 6,
          "process_name": "svchost.exe",
          "windows_service_name": "TermService",
          "user_name": "NETWORK SERVICE"
        },
        "num_connections": 1,
        "state": "timed out",
        "timestamp_range": {
          "first_detected": "2022-02-03T22:33:50Z",
          "last_detected": "2022-02-03T22:33:50Z"
        },
