=== dsommerville-illumio/resilient-community-apps/fn_illumio/payload_samples/illumio_update_workload_enforcement_mode/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "object",
      "properties": {
        "errors": {
          "type": "array"
        },
        "workloads": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "illumio_enforcement_mode": {
          "type": "string"
        },
        "illumio_workload_hrefs": {
          "type": "string"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== dsommerville-illumio/resilient-community-apps/fn_illumio/payload_samples/illumio_update_workload_enforcement_mode/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "errors": [],
    "workloads": [
      "/orgs/28/workloads/1fbe5dee-8bde-49cc-9a8f-6870a05a716e",
      "/orgs/28/workloads/424b21c5-f8c7-40d0-b2bd-53fd38f606c6",
      "/orgs/28/workloads/0c2ee289-3f07-4842-97fa-2acf9d8f837c",
      "/orgs/28/workloads/de7c3ea1-6d5c-4737-8cfc-27a53270ea61",
      "/orgs/28/workloads/0aaf4c39-a956-4e19-b606-b866616cc476",
      "/orgs/28/workloads/a3bd7c69-a918-4f46-b517-c7a45f3114d5",
      "/orgs/28/workloads/20c1520f-215c-43a4-8b3a-362171d0ea06",
      "/orgs/28/workloads/fa2f3f9b-a899-4902-850f-126daf86b8b1",
      "/orgs/28/workloads/e815fc29-657d-43d7-82d9-758f6d6a59fa",
      "/orgs/28/workloads/71000830-be4d-49a7-853e-7a555eccb2d3",
      "/orgs/28/workloads/64356c9b-e09f-44ac-9d8c-321a500dfc5f",
      "/orgs/28/workloads/df01225c-e429-4f8f-892f-7c83c031add9",
      "/orgs/28/workloads/77cb9723-1b89-495a-a058-73f39802dcd8",
      "/orgs/28/workloads/7c2e50b1-f447-4a48-ba58-0f517b7c7380",
      "/orgs/28/workloads/a0a1a599-80aa-4660-90ed-950ca0767568",
      "/orgs/28/workloads/932197f6-af89-42c5-96cc-682edf59b88e",
      "/orgs/28/workloads/7c78ab4b-ced8-43a7-bf1f-5e92f89138bf",
      "/orgs/28/workloads/431ff8e6-39ca-420a-be68-a8b45a1644fd",
      "/orgs/28/workloads/e08b424e-da53-46b4-9f78-1915867d2cfb",
      "/orgs/28/workloads/f38c64de-d437-4037-89f8-2bed85debdf0",
      "/orgs/28/workloads/44346183-79ce-47a3-908d-92cd150a0446",
      "/orgs/28/workloads/d911ba88-7410-4945-8124-c140ee644fe3",
      "/orgs/28/workloads/cc34db03-9750-40ce-85e5-1eec865c9392",
      "/orgs/28/workloads/337b81e0-4e93-40f7-bcb2-844e3084465c",
      "/orgs/28/workloads/92a29d45-25ee-4b10-af92-27fd9c6d8969",
      "/orgs/28/workloads/235ce8f7-9a52-4da9-a831-1c58b01ffcab",
      "/orgs/28/workloads/2fca97cd-f836-4f28-972b-b112b0c647d6",
      "/orgs/28/workloads/6567900a-b49f-43cc-93a7-c892da39aad1",
      "/orgs/28/workloads/51cbcd7d-bd05-4485-a08b-5205ce24992a",
      "/orgs/28/workloads/71d7635d-6e65-4e57-a0c7-7ddb50af30ac",
      "/orgs/28/workloads/22c9be04-fa5d-4499-a663-b1bd8863038a",
      "/orgs/28/workloads/e524a0a2-afc2-497a-bf45-b4823afa6012",
      "/orgs/28/workloads/1a5ea894-c5c4-444b-9b88-5a05d8d4c310",
      "/orgs/28/workloads/b9e460b9-df76-478a-86fc-f9aa1f7f2af6"
    ]
  },
  "raw": null,
  "inputs": {
    "illumio_enforcement_mode": "selective",
    "illumio_workload_hrefs": "/orgs/28/workloads/1fbe5dee-8bde-49cc-9a8f-6870a05a716e,/orgs/28/workloads/424b21c5-f8c7-40d0-b2bd-53fd38f606c6,/orgs/28/workloads/0c2ee289-3f07-4842-97fa-2acf9d8f837c,/orgs/28/workloads/de7c3ea1-6d5c-4737-8cfc-27a53270ea61,/orgs/28/workloads/0aaf4c39-a956-4e19-b606-b866616cc476,/orgs/28/workloads/a3bd7c69-a918-4f46-b517-c7a45f3114d5,/orgs/28/workloads/20c1520f-215c-43a4-8b3a-362171d0ea06,/orgs/28/workloads/fa2f3f9b-a899-4902-850f-126daf86b8b1,/orgs/28/workloads/e815fc29-657d-43d7-82d9-758f6d6a59fa,/orgs/28/workloads/71000830-be4d-49a7-853e-7a555eccb2d3,/orgs/28/workloads/64356c9b-e09f-44ac-9d8c-321a500dfc5f,/orgs/28/workloads/df01225c-e429-4f8f-892f-7c83c031add9,/orgs/28/workloads/77cb9723-1b89-495a-a058-73f39802dcd8,/orgs/28/workloads/7c2e50b1-f447-4a48-ba58-0f517b7c7380,/orgs/28/workloads/a0a1a599-80aa-4660-90ed-950ca0767568,/orgs/28/workloads/932197f6-af89-42c5-96cc-682edf59b88e,/orgs/28/workloads/7c78ab4b-ced8-43a7-bf1f-5e92f89138bf,/orgs/28/workloads/431ff8e6-39ca-420a-be68-a8b45a1644fd,/orgs/28/workloads/e08b424e-da53-46b4-9f78-1915867d2cfb,/orgs/28/workloads/f38c64de-d437-4037-89f8-2bed85debdf0,/orgs/28/workloads/44346183-79ce-47a3-908d-92cd150a0446,/orgs/28/workloads/d911ba88-7410-4945-8124-c140ee644fe3,/orgs/28/workloads/cc34db03-9750-40ce-85e5-1eec865c9392,/orgs/28/workloads/337b81e0-4e93-40f7-bcb2-844e3084465c,/orgs/28/workloads/92a29d45-25ee-4b10-af92-27fd9c6d8969,/orgs/28/workloads/235ce8f7-9a52-4da9-a831-1c58b01ffcab,/orgs/28/workloads/2fca97cd-f836-4f28-972b-b112b0c647d6,/orgs/28/workloads/6567900a-b49f-43cc-93a7-c892da39aad1,/orgs/28/workloads/51cbcd7d-bd05-4485-a08b-5205ce24992a,/orgs/28/workloads/71d7635d-6e65-4e57-a0c7-7ddb50af30ac,/orgs/28/workloads/22c9be04-fa5d-4499-a663-b1bd8863038a,/orgs/28/workloads/e524a0a2-afc2-497a-bf45-b4823afa6012,/orgs/28/workloads/1a5ea894-c5c4-444b-9b88-5a05d8d4c310,/orgs/28/workloads/b9e460b9-df76-478a-86fc-f9aa1f7f2af6"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-illumio",
    "package_version": "1.1.0",
    "host": "C02G82JEMD6R",
    "execution_time_ms": 1117,
    "timestamp": "2022-03-09 23:58:34"
  }
}
