=== dsommerville-illumio/resilient-community-apps/fn_illumio/payload_samples/illumio_create_ruleset/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "object",
      "properties": {
        "href": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "created_at": {
          "type": "string"
        },
        "updated_at": {
          "type": "string"
        },
        "created_by": {
          "type": "object",
          "properties": {
            "href": {
              "type": "string"
            }
          }
        },
        "updated_by": {
          "type": "object",
          "properties": {
            "href": {
              "type": "string"
            }
          }
        },
        "caps": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "enabled": {
          "type": "boolean"
        },
        "scopes": {
          "type": "array",
          "items": {
            "type": "array"
          }
        },
        "rules": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "href": {
                "type": "string"
              },
              "created_at": {
                "type": "string"
              },
              "updated_at": {
                "type": "string"
              },
              "created_by": {
                "type": "object",
                "properties": {
                  "href": {
                    "type": "string"
                  }
                }
              },
              "updated_by": {
                "type": "object",
                "properties": {
                  "href": {
                    "type": "string"
                  }
                }
              },
              "ingress_services": {
                "type": "array"
              },
              "providers": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "virtual_service": {
                      "type": "object",
                      "properties": {
                        "href": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              },
              "consumers": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "ip_list": {
                      "type": "object",
                      "properties": {
                        "href": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              },
              "enabled": {
                "type": "boolean"
              },
              "resolve_labels_as": {
                "type": "object",
                "properties": {
                  "providers": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "consumers": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                }
              },
              "sec_connect": {
                "type": "boolean"
              },
              "stateless": {
                "type": "boolean"
              },
              "machine_auth": {
                "type": "boolean"
              },
              "consuming_security_principals": {
                "type": "array"
              },
              "unscoped_consumers": {
                "type": "boolean"
              },
              "network_type": {
                "type": "string"
              }
            }
          }
        },
        "ip_tables_rules": {
          "type": "array"
        }
      }
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "illumio_ruleset_name": {
          "type": "string"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== dsommerville-illumio/resilient-community-apps/fn_illumio/payload_samples/illumio_create_ruleset/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "href": "/orgs/28/sec_policy/active/rule_sets/12269",
    "name": "RS-IBM-SOAR-3389-TCP",
    "created_at": "2022-03-04T18:46:12.676Z",
    "updated_at": "2022-03-04T18:46:14.377Z",
    "created_by": {
      "href": "/users/520"
    },
    "updated_by": {
      "href": "/users/520"
    },
    "caps": [
      "write",
      "provision"
    ],
    "enabled": true,
    "scopes": [
      []
    ],
    "rules": [
      {
        "href": "/orgs/28/sec_policy/active/rule_sets/12269/sec_rules/20760",
        "created_at": "2022-03-04T18:46:14.367Z",
        "updated_at": "2022-03-04T18:46:14.377Z",
        "created_by": {
          "href": "/users/520"
        },
        "updated_by": {
          "href": "/users/520"
        },
        "ingress_services": [],
        "providers": [
          {
            "virtual_service": {
              "href": "/orgs/28/sec_policy/active/virtual_services/0447a982-ba9d-462d-bfc7-29bdac3627c3"
            }
          }
        ],
        "consumers": [
          {
            "ip_list": {
              "href": "/orgs/28/sec_policy/active/ip_lists/105"
            }
          }
        ],
        "enabled": true,
        "resolve_labels_as": {
          "providers": [
            "virtual_services"
          ],
          "consumers": [
            "workloads"
          ]
        },
        "sec_connect": false,
        "stateless": false,
        "machine_auth": false,
        "consuming_security_principals": [],
        "unscoped_consumers": false,
        "network_type": "brn"
      }
    ],
    "ip_tables_rules": []
  },
  "raw": null,
  "inputs": {
    "illumio_ruleset_name": "RS-IBM-SOAR-3389-TCP"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-illumio",
    "package_version": "1.1.0",
    "host": "C02G82JEMD6R",
    "execution_time_ms": 536,
    "timestamp": "2022-03-09 23:58:20"
  }
}
