=== dsommerville-illumio/resilient-community-apps/fn_illumio/payload_samples/illumio_get_ip_list/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "object",
      "properties": {
        "href": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "created_at": {
          "type": "string"
        },
        "updated_at": {
          "type": "string"
        },
        "created_by": {
          "type": "object",
          "properties": {
            "href": {
              "type": "string"
            }
          }
        },
        "updated_by": {
          "type": "object",
          "properties": {
            "href": {
              "type": "string"
            }
          }
        },
        "ip_ranges": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "from_ip": {
                "type": "string"
              },
              "exclusion": {
                "type": "boolean"
              }
            }
          }
        }
      }
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "illumio_ip_list_name": {
          "type": "string"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== dsommerville-illumio/resilient-community-apps/fn_illumio/payload_samples/illumio_get_ip_list/output_json_example.json
{
    "version": 2.0,
    "success": true,
    "reason": null,
    "content": {
        "href": "/orgs/1/sec_policy/active/ip_lists/1334",
        "name": "Any (0.0.0.0/0 and ::/0)",
        "created_at": "2021-09-13T15:03:07.000Z",
        "updated_at": "2021-09-13T15:03:07.015Z",
        "created_by": {
            "href": "/users/0"
        },
        "updated_by": {
            "href": "/users/0"
        },
        "ip_ranges": [
            {
                "from_ip": "0.0.0.0/0",
                "exclusion": false
            },
            {
                "from_ip": "::/0",
                "exclusion": false
            }
        ]
    },
    "raw": null,
    "inputs": {
        "illumio_ip_list_name": "Any (0.0.0.0/0 and ::/0)"
    },
    "metrics": {
        "version": "1.0",
        "package": "fn-illumio",
        "package_version": "1.0.0",
        "host": "C02G82JEMD6R",
        "execution_time_ms": 811,
        "timestamp": "2022-01-07 10:22:52"
    }
}
